name: Deploy Gateway to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_GATEWAY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_GATEWAY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 (Gateway)
        run: |
          ssh -o ServerAliveInterval=30 ${{ secrets.EC2_GATEWAY_USER }}@${{ secrets.EC2_GATEWAY_HOST }} << 'EOF'
            set -e

            # 디렉토리 없으면 clone
            if [ ! -d ~/gateway ]; then
              git clone git@github.com:Hminchae/msa-gateway.git ~/gateway
            fi

            cd ~/gateway
            git pull origin develop

            ./gradlew clean bootJar --info

            # systemd 서비스 재시작
            sudo systemctl restart gateway || echo "서비스가 없으면 무시"

            # 세션 명확히 종료
            exit
          EOF
